name: ecoville_bloc
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.2.1
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.9.2
  connectivity_plus: ^4.0.2
  dio: ^5.3.2
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  firebase_remote_config: ^4.2.6
  firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_google_places: ^0.3.0
  flutter_local_notifications: ^15.1.1
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  geolocator: ^10.0.1
  go_router: ^10.2.0
  google_api_headers: ^1.6.0
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  lottie: ^2.6.0
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  url_launcher: ^6.1.14
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/categories/
