// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvT4sVh9epwvdwqoVXYnFIX_ljXQa_S_Q',
    appId: '1:152915277921:android:d4c5f185c9366881f7d220',
    messagingSenderId: '152915277921',
    projectId: 'ecoville-1b1d1',
    databaseURL: 'https://ecoville-1b1d1-default-rtdb.firebaseio.com',
    storageBucket: 'ecoville-1b1d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuAQC2q0V5dRKCSZpMsK2xiFqX-uRL7es',
    appId: '1:152915277921:ios:d899eadb6d1acd93f7d220',
    messagingSenderId: '152915277921',
    projectId: 'ecoville-1b1d1',
    databaseURL: 'https://ecoville-1b1d1-default-rtdb.firebaseio.com',
    storageBucket: 'ecoville-1b1d1.appspot.com',
    iosClientId: '152915277921-ifoakrjuors1ppbcu8rqm42vckq0i89u.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecovilleBloc',
  );
}
